version: '3.8'

services:

  mysql:
    image: mysql
    container_name: mysql-database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: 12349
      - MYSQL_DATABASE: studentdetailsdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend-services:
    image: studentdetailsbackend:0.1
    container_name: backendcontainer
    #build:
    #  context: .
    # dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
     - "8090:8088"
    environment:
      - SPRING_DATASOURCE_URL=jjdbc:mysql://mysql:3306/studentdetailsdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12349


  frontend-services:
    image: studentdetailsfrontend:0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file watching
    volumes:
      - ./frontend/src:/app/src:ro
    depends_on:
       backend-services
  